skip_tags: true

version: 5.0.{build}

os: Visual Studio 2017

# Done here so that the ES server has the time to initialize fully
install:
  - ps: .\run_es.ps1

configuration: release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
  - cmd: paket restore

build_script:
  - cmd: build.cmd

artifacts:
  - path: '**\*.nupkg'

for:
-
  branches:
    only:
      - master

  deploy:
    provider: NuGet
    api_key:
      secure: Ax/Zt3hfzLf7jMzb9VqiCsTtGCr3c+sf6pozg3KrCm/d+qZnY2IWFmmbQYws5Frh
    skip_symbols: true
    artifact: /.*\.nupkg/
