version: 1.0.{build}

os: Visual Studio 2015

install:
 - ps: .\run_es.ps1

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
- paket restore

build:
  publish_nuget: true
  project: FluentNest.sln

deploy:
  provider: NuGet
  api_key:
    secure: Ax/Zt3hfzLf7jMzb9VqiCsTtGCr3c+sf6pozg3KrCm/d+qZnY2IWFmmbQYws5Frh
  skip_symbols: true
  artifact: /.*\.nupkg/
